name: Deploy to ECR

on:
 
  push:
    branches: [ feature1 ]

env:
  ECR_REPOSITORY: flask-app
  EKS_CLUSTER_NAME: eks-cluster 
  AWS_REGION: ap-northeast-3

jobs:
  
  build:
    
    name: Deployment
    runs-on: self-hosted

    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Build Docker Image
      run: docker build --build-arg ENV=prod -t local-image:latest -f docker/Dockerfile .

    - name: scan image with trivy
      uses: aquasecurity/trivy-action@0.24.0
      with: 
        image-ref: local-image:latest
        format: "sarif"
        severity: "CRITICAL,HIGH"
        vuln-type: os,library
        output: trivy-result
        exit-code: '1'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-result'

