name: Deploy to ECR

on:
 
  push:
    branches: [ feature1 ]

env:
  ECR_REPOSITORY: flask-app
  EKS_CLUSTER_NAME: eks-cluster 
  AWS_REGION: ap-northeast-3

jobs:
  
  build:
    
    name: Deployment
    runs-on: self-hosted

    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Build Docker Image
      run: docker build --build-arg ENV=prod -t local-image:latest -f docker/Dockerfile .

    - name: scan image with trivy
      uses: aquasecurity/trivy-action@0.24.0
      with: 
        image-ref: local-image:latest
        format: "table"
        severity: "CRITICAL,HIGH"
        output: trivy-result
        exit-code: '1'

    - id: trivy_output
      name: output_file
      if: failure()
      run: |
        output_data=$(cat ./trivy-result)
        output_data="${output_data//$'\n'/\\n}"
        echo "::set-output name=std_out::$output_data"

    - name: create_issue
      if: failure()
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const { GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID } = process.env
            var trivy_output_data = `{{ steps.trivy_output.outputs.std_out }}`
            console.log(trivy_output_data);
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security Alert',
              body: "```"+`${trivy_output_data}`+"```",
              })
